### ISSUE TITLE
avea.Registry is not a constructor

### ISSUE THREAD

**Issue by pattyland** [Marmelatze/avea_node#7]
Hi, I just installed your avea_server and it fails to start:

`/usr/lib/node_modules/avea_server/index.js:23
const registry = new avea.Registry();
                 ^

TypeError: avea.Registry is not a constructor
    at Object.<anonymous> (/usr/lib/node_modules/avea_server/index.js:23:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
`

There is no mention of an avea.Registry, neither here nor in the version in the npm registry!

**Comment by Marmelatze** [comment]
See the avea_server branch. https://github.com/Marmelatze/avea_node/blob/avea_server/lib/registry.js

It was first run to make a http around this library (see. https://github.com/Marmelatze/avea_server)

**Comment by pattyland** [comment]
Awesome, the server is working great with the code from this branch! Is there a reason why this is not merged into the master branch?
